### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Ciao121** [wcerfgba/gridball#1]
Hi,
this happens when I try to opn from the browser on a remote server. Does not happens if I try on localhost. Any idea?

Thank you!

**Comment by Ciao121** [comment]
localhots is a windows pc; remote host is a debian pc. Maybe owner / permission problem?

**Comment by Ciao121** [comment]
I had this problem:
`cannot run in wd gridball@0.0.0 brunch build --production (wd=/gridball)`
solved using
`npm install --unsafe-perm`

**Comment by wcerfgba** [comment]
One issue you will have building on Windows is that the `precompile.sh` script in the repository root is written in bash. That script just concatenates the files `client/_precompile/common.js` and `client/_precompile/index.js` to make `client/index.js`, so you will need to do that manually before building with Brunch.

You cannot GET / because the Brunch build is failing and not producing output, which should go in `public/`, which is where express serves from. Can you get any more output from the build process, perhaps with `brunch build --production --debug`?

Thanks.

**Comment by Ciao121** [comment]
The problem was due this: https://docs.npmjs.com/misc/scripts#user

> If npm was invoked with root privileges, then it will change the uid to the user account or uid specified by the user config, which defaults to nobody. Set the unsafe-perm flag to run scripts with root privileges.

It's fine now.

**Comment by wcerfgba** [comment]
You should be able to install it without `--unsafe-perm`; possibly a file permissions issue as you said. If it works for you and you're happy with the `--unsafe-perm` flag then that's fine. Closing for now.
